### ISSUE TITLE
issue restarting the dev server

### ISSUE THREAD

**Issue by Sandros94** [pruvious/pruvious#17]
I feel like I'm doing something dumb, but it seems that I'm not able to restart the dev server after I've stopped it the first time (fresh `nlx pruvious@latest pruvious-test`).

[My test repo](https://github.com/sandros94/pruvious-test)
  - `nvm`: `1.1.11`
  - `node`: `20.11.1`
  - `@antfu/ni`: `0.21.12` (doesn't seem to be the problem, even using `pnpm` directly creates the same errors)

<details>
  <summary>Terminal Log</summary>
  
  ```powershell
  PS A:\github\sandros94\pruvious-test> nr dev

  > nuxt-app@ dev A:\github\sandros94\pruvious-test
  > pruvious dev

  Nuxt 3.10.3 with Nitro 2.9.4                                                                                                                                                              15:02:07
                                                                                                                                                                                            15:02:07
    ➜ Local:    http://localhost:3000/
    ➜ Network:  use --host to expose

    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               15:02:09

  ✔ Database synced in 1391 ms                                                                                                                                                    pruvious 15:02:11
  ✔ Pruvious built in 903 ms                                                                                                                                                      pruvious 15:02:11   
  ℹ Vite server warmed up in 601ms                                                                                                                                                         15:02:12
  ℹ Vite client warmed up in 1030ms                                                                                                                                                        15:02:13
  ✔ Nuxt Nitro server built in 2432 ms                                                                                                                                               nitro 15:02:15
  ℹ .env changed, restarting server...                                                                                                                                                     15:02:16
  ✔ Pruvious built in 18 ms                                                                                                                                                       pruvious 15:02:16
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             15:02:16
  ℹ .env changed, restarting server... (x2)                                                                                                                                                15:02:16
  ℹ .env changed, restarting server... (x3)                                                                                                                                                15:02:16   
  ℹ server restarted.                                                                                                                                                                      15:02:16   
  ℹ server restarted. (x2)                                                                                                                                                                 15:02:16
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       15:02:16   

  ERROR  [unhandledRejection] kill ENOSYS                                                                                                                                                  15:02:16  

    at ChildProcess.kill (node:internal/child_process:509:13)
    at kill (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:246:17)
    at restart (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:251:5)
    at ChildProcess.<anonymous> (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:280:9)
    at ChildProcess.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

  FATAL ERROR: Error::Error napi_define_properties
  ----- Native stack trace -----


  ERROR  [unhandledRejection] kill ENOSYS                                                                                                                                                  15:02:16  

    at ChildProcess.kill (node:internal/child_process:509:13)
    at kill (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:246:17)
    at restart (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:251:5)
    at ChildProcess.<anonymous> (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:280:9)
    at ChildProcess.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)


  ERROR  [unhandledRejection] kill ENOSYS                                                                                                                                                  15:02:16  

    at ChildProcess.kill (node:internal/child_process:509:13)
    at kill (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:246:17)
    at restart (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:251:5)
    at ChildProcess.<anonymous> (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:280:9)
    at ChildProcess.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

  FATAL ERROR: Error::Error napi_define_properties
  ----- Native stack trace -----


  ERROR  [unhandledRejection] kill ENOSYS                                                                                                                                                  15:02:16  

    at ChildProcess.kill (node:internal/child_process:509:13)
    at kill (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:246:17)
    at restart (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:251:5)
    at ChildProcess.<anonymous> (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:280:9)
    at ChildProcess.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

  1: 00007FF6751771AB node::SetCppgcReference+16075
  2: 00007FF6750EDCC6 v8::base::CPU::num_virtual_address_bits+79190
  3: 00007FF6750EFFDC node::OnFatalError+252
  4: 00007FF675128FDC napi_fatal_error+156
  5: 00007FFF061F1B17
  6: 00007FFF061F1AF8
  7: 00007FFF0620D7DF napi_register_module_v1+18479
  8: 00007FF675125DF2 node_module_register+3442
  9: 00007FF6751DF4B0 uv_timer_stop+800
  10: 00007FF6751DF69A uv_timer_stop+1290
  11: 00007FF6751DB91B uv_update_time+491
  12: 00007FF6751DB494 uv_run+900
  13: 00007FF6751AC382 node::SpinEventLoop+402
  14: 00007FF674FEA184 RSA_meth_get_flags+159812
  15: 00007FF674FE51B8 RSA_meth_get_flags+139384
  16: 00007FF6751C9B6D uv_poll_stop+237
  17: 00007FF676365180 inflateValidate+153328
  18: 00007FFF5CFE257D BaseThreadInitThunk+29
  19: 00007FFF5F0AAA58 RtlUserThreadStart+40

  ERROR  [unhandledRejection] read ECONNRESET                                                                                                                                              15:02:16  

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
  ```
</details>

**Comment by murisceman** [comment]
You mean you cannot restart it manually with `nr dev` after stopping it, or it doesn't restart automatically when you make changes in your project files? Also, do you use `pruvious dev` in your `dev` script in `package.json`?

**Comment by Sandros94** [comment]
> Also, do you use `pruvious dev` in your `dev` script in `package.json`?

yes

> You mean you cannot restart it manually with `nr dev` after stopping it, or it doesn't restart automatically when you make changes in your project files?

restart manually after stopping it. The first `nr dev` after project `init` works perfectly and I can access the dashboard and all, but then if I stop the dev server and restart it it doesn't work.

Also, for some reason now it is doing something different: the dev server only crashes when I try to open up `localhost:3000`

<details>
  <summary>Termina Log</summary>

  ```powershell
  PS A:\github\sandros94\pruvious-test> nr dev

  > nuxt-app@ dev A:\github\sandros94\pruvious-test
  > pruvious dev

  Nuxt 3.10.3 with Nitro 2.9.4                                                                                                                                                              16:58:04
                                                                                                                                                                                            16:58:04
    ➜ Local:    http://localhost:3000/
    ➜ Network:  use --host to expose

    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               16:58:06

  ✔ Database synced in 1302 ms                                                                                                                                                    pruvious 16:58:08
  ✔ Pruvious built in 676 ms                                                                                                                                                      pruvious 16:58:08   
  ℹ Vite server warmed up in 2895ms                                                                                                                                                        16:58:12
  ℹ Vite client warmed up in 3062ms                                                                                                                                                        16:58:12   
  ✔ Nuxt Nitro server built in 3359 ms                                                                                                                                               nitro 16:58:14

  --- here I open the browser ---

  ✔ Pruvious built in 20 ms                                                                                                                                                       pruvious 16:58:15
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             16:58:15
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       16:58:15
  [16:58:15] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       16:58:15   
  [16:58:15] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
  ----- Native stack trace -----

  FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
  ----- Native stack trace -----

  1: 00007FF6751771AB node::SetCppgcReference+16075
  2: 00007FF6750EDCC6 v8::base::CPU::num_virtual_address_bits+79190
  3: 00007FF6750EFFDC node::OnFatalError+252
  4: 00007FF675128FDC napi_fatal_error+156
  5: 00007FFF061C1B17
  6: 00007FFF061C1F80
  7: 00007FFF061DD7E8 napi_register_module_v1+18488
  8: 00007FF675125DF2 node_module_register+3442
  9: 00007FF6751DF4B0 uv_timer_stop+800
  10: 00007FF6751DF69A uv_timer_stop+1290
  11: 00007FF6751DB91B uv_update_time+491
  12: 00007FF6751DB494 uv_run+900
  13: 00007FF675155581 node_api_throw_syntax_error+69617
  14: 00007FF67516CE2D node_api_throw_syntax_error+166045
  15: 00007FF6751A8CB5 node::FreeEnvironment+133
  16: 00007FF674FEA1E8 RSA_meth_get_flags+159912
  17: 00007FF674FE51B8 RSA_meth_get_flags+139384
  18: 00007FF6751C9B6D uv_poll_stop+237
  19: 00007FF676365180 inflateValidate+153328
  20: 00007FFF5CFE257D BaseThreadInitThunk+29
  21: 00007FFF5F0AAA58 RtlUserThreadStart+40
  ```
</details>

**Comment by murisceman** [comment]
Does `nuxt dev` work for you instead of `pruvious dev`?

**Comment by Sandros94** [comment]
nope, nuxt restarts a few time (triggered by a config change), then crashes

<details>
  <summary>Termina Log</summary>

  ```powershell
  PS A:\github\sandros94\pruvious-test> nr dev

  > nuxt-app@ dev A:\github\sandros94\pruvious-test
  > nuxt dev

  Nuxt 3.10.3 with Nitro 2.9.4                                                                                                                                                              17:12:48
                                                                                                                                                                                            17:12:48
    ➜ Local:    http://localhost:3000/
    ➜ Network:  use --host to expose

    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               17:12:49

  ✔ Database synced in 1398 ms                                                                                                                                                    pruvious 17:12:52
  ✔ Pruvious built in 704 ms                                                                                                                                                      pruvious 17:12:52   
  ℹ Vite server warmed up in 3032ms                                                                                                                                                        17:12:56
  ℹ Vite client warmed up in 3199ms                                                                                                                                                        17:12:56   
  ✔ Nuxt Nitro server built in 3108 ms                                                                                                                                               nitro 17:12:58
  ✔ Pruvious built in 17 ms                                                                                                                                                       pruvious 17:12:59
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             17:12:59
    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               17:12:59

  ✔ Pruvious built in 651 ms                                                                                                                                                      pruvious 17:13:00
  ℹ Vite client warmed up in 3042ms                                                                                                                                                        17:13:03
  ℹ Vite server warmed up in 2948ms                                                                                                                                                        17:13:03   
  ✔ Nuxt Nitro server built in 3125 ms                                                                                                                                               nitro 17:13:05
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             17:13:05
    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               17:13:05

  ✔ Pruvious built in 246 ms                                                                                                                                                      pruvious 17:13:05
  ℹ Vite client warmed up in 3270ms                                                                                                                                                        17:13:09
  ℹ Vite server warmed up in 3188ms                                                                                                                                                        17:13:09   
  ✔ Nuxt Nitro server built in 3475 ms                                                                                                                                               nitro 17:13:11
  ✔ Pruvious built in 14 ms                                                                                                                                                       pruvious 17:13:12
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             17:13:12
  FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
  ----- Native stack trace -----

  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       17:13:12
  [17:13:12] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       17:13:12   
  [17:13:12] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  1: 00007FF6751771AB node::SetCppgcReference+16075
  2: 00007FF6750EDCC6 v8::base::CPU::num_virtual_address_bits+79190
  3: 00007FF6750EFFDC node::OnFatalError+252
  4: 00007FF675128FDC napi_fatal_error+156
  5: 00007FFF06311B17
  6: 00007FFF06311F80
  7: 00007FFF0632D7E8 napi_register_module_v1+18488
  8: 00007FF675125DF2 node_module_register+3442
  9: 00007FF6751DF4B0 uv_timer_stop+800
  10: 00007FF6751DF69A uv_timer_stop+1290
  11: 00007FF6751DB91B uv_update_time+491
  12: 00007FF6751DB494 uv_run+900
  13: 00007FF675155581 node_api_throw_syntax_error+69617
  14: 00007FF67516CE2D node_api_throw_syntax_error+166045
  15: 00007FF6751A8CB5 node::FreeEnvironment+133
  16: 00007FF674FEA1E8 RSA_meth_get_flags+159912
  17: 00007FF674FE51B8 RSA_meth_get_flags+139384
  18: 00007FF6751C9B6D uv_poll_stop+237
  19: 00007FF676365180 inflateValidate+153328
  20: 00007FFF5CFE257D BaseThreadInitThunk+29
  21: 00007FFF5F0AAA58 RtlUserThreadStart+40
   ELIFECYCLE  Command failed with exit code 134.
  ```
</details>

**Comment by murisceman** [comment]
There might be an infinite restart loop caused by `nuxt.config.ts updated. Restarting nuxt...`. You're on Windows, right? Are you starting the server via VSCode terminal? If yes, could you try running it from ﻿cmd.exe or PowerShell?

**Comment by Sandros94** [comment]
> You're on Windows, right? Are you starting the server via VSCode terminal? If yes, could you try running it from ﻿cmd.exe or PowerShell?

Yes I'm on windows, but even using the terminal (and not the vscode integrated one) produces the same output

**Comment by murisceman** [comment]
Just tried out your repository on my Windows machine, and it works flawlessly.

![image](https://github.com/pruvious/pruvious/assets/470407/24407ed6-1377-47a6-aee9-1b8a140983f8)

I noticed duplicate dependencies in your `package.json`. Could you try using this:

```json
{
  "name": "nuxt-app",
  "type": "module",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "pruvious dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.10.3",
    "pruvious": "^3.10.8"
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  }
}
```

**Comment by Sandros94** [comment]
The duplicated dependencies don't seem to be the issue:
  <details>
  <summary><code>pruvious dev</code></summary>

  ```powershell
  PS A:\github\sandros94\pruvious-test> nr dev

  > nuxt-app@ dev A:\github\sandros94\pruvious-test
  > pruvious dev

  Nuxt 3.10.3 with Nitro 2.9.4                                                                                                                                                              18:43:50  
                                                                                                                                                                                            18:43:50  
    ➜ Local:    http://localhost:3000/
    ➜ Network:  use --host to expose

    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               18:43:51  

  ✔ Database synced in 1230 ms                                                                                                                                                    pruvious 18:43:54   
  ✔ Pruvious built in 674 ms                                                                                                                                                      pruvious 18:43:54   
  ℹ Vite client warmed up in 3144ms                                                                                                                                                        18:43:57
  ℹ Vite server warmed up in 2983ms                                                                                                                                                        18:43:57
  ✔ Nuxt Nitro server built in 3095 ms                                                                                                                                               nitro 18:43:59
  ✔ Pruvious built in 18 ms                                                                                                                                                       pruvious 18:44:09
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             18:44:09
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       18:44:09
  [18:44:09] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       18:44:09
  [18:44:09] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  FATAL ERROR: Error::Error napi_define_properties
  ----- Native stack trace -----

  FATAL ERROR: Error::Error napi_define_properties
  ----- Native stack trace -----

  1: 00007FF6751771AB node::SetCppgcReference+16075
  2: 00007FF6750EDCC6 v8::base::CPU::num_virtual_address_bits+79190
  3: 00007FF6750EFFDC node::OnFatalError+252
  4: 00007FF675128FDC napi_fatal_error+156
  5: 00007FFEBBB51B17 
  6: 00007FFEBBB51AF8 
  7: 00007FFEBBB6D7DF napi_register_module_v1+18479
  8: 00007FF675125DF2 node_module_register+3442
  9: 00007FF6751DF4B0 uv_timer_stop+800
  10: 00007FF6751DF69A uv_timer_stop+1290
  11: 00007FF6751DB91B uv_update_time+491
  12: 00007FF6751DB494 uv_run+900
  13: 00007FF6751AC382 node::SpinEventLoop+402
  14: 00007FF674FEA184 RSA_meth_get_flags+159812
  15: 00007FF674FE51B8 RSA_meth_get_flags+139384
  16: 00007FF6751C9B6D uv_poll_stop+237
  17: 00007FF676365180 inflateValidate+153328
  18: 00007FFF5CFE257D BaseThreadInitThunk+29
  19: 00007FFF5F0AAA58 RtlUserThreadStart+40

  ERROR  [unhandledRejection] read ECONNRESET                                                                                                                                              18:44:09  

    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
  ```
  </details>

  <details>
  <summary><code>nuxt dev</code></summary>

  ```powershell
  PS A:\github\sandros94\pruvious-test> nr dev

  > nuxt-app@ dev A:\github\sandros94\pruvious-test
  > nuxt dev

  Nuxt 3.10.3 with Nitro 2.9.4                                                                                                                                                              18:44:33
                                                                                                                                                                                            18:44:33
    ➜ Local:    http://localhost:3000/
    ➜ Network:  use --host to expose

    ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)                                                                                                                               18:44:35

  ✔ Database synced in 1235 ms                                                                                                                                                    pruvious 18:44:37
  ✔ Pruvious built in 673 ms                                                                                                                                                      pruvious 18:44:37   
  ℹ Vite client warmed up in 3145ms                                                                                                                                                        18:44:41
  ℹ Vite server warmed up in 2983ms                                                                                                                                                        18:44:41   
  ✔ Nuxt Nitro server built in 3176 ms                                                                                                                                               nitro 18:44:43
  ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                             18:44:48
  FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
  ----- Native stack trace -----


  ERROR  [unhandledRejection] Nuxt instance is unavailable!                                                                                                                                18:44:48  

    at useNuxt (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/@nuxt+kit@3.10.3/node_modules/@nuxt/kit/dist/index.mjs:32:11)
    at resolveFields (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:1792:16)
    at generateDotPruvious (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:3009:18)
    at debounce.leading (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:3101:27)
    at _applyPromised (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:19)
    at applyFn (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:15:22)
    at /A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:45:24
    at new Promise (<anonymous>)
    at /A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:33:12
    at Timeout._onTimeout (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:3160:7)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)


  ERROR  [unhandledRejection] Nuxt instance is unavailable!                                                                                                                                18:44:48  

    at useNuxt (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/@nuxt+kit@3.10.3/node_modules/@nuxt/kit/dist/index.mjs:32:11)
    at resolveFields (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:1792:16)
    at generateDotPruvious (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:3009:18)
    at debounce.leading (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:3101:27)
    at _applyPromised (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:19)
    at applyFn (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:15:22)
    at /A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:45:24
    at new Promise (<anonymous>)
    at /A:/github/sandros94/pruvious-test/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:33:12
    at Timeout._onTimeout (/A:/github/sandros94/pruvious-test/node_modules/.pnpm/pruvious@3.10.8_vue@3.4.21/node_modules/pruvious/dist/module.mjs:3160:7)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       18:44:48
  [18:44:48] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  ℹ hmr update /.nuxt/app.config.mjs                                                                                                                                                       18:44:48   
  [18:44:48] ℹ changed tsconfig file detected: A:\github\sandros94\pruvious-test\.nuxt\tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
  1: 00007FF6751771AB node::SetCppgcReference+16075
  2: 00007FF6750EDCC6 v8::base::CPU::num_virtual_address_bits+79190
  3: 00007FF6750EFFDC node::OnFatalError+252
  4: 00007FF675128FDC napi_fatal_error+156
  5: 00007FFF062B1B17
  6: 00007FFF062B1F80
  7: 00007FFF062CD7E8 napi_register_module_v1+18488
  8: 00007FF675125DF2 node_module_register+3442
  9: 00007FF6751DF4B0 uv_timer_stop+800
  10: 00007FF6751DF69A uv_timer_stop+1290
  11: 00007FF6751DB91B uv_update_time+491
  12: 00007FF6751DB494 uv_run+900
  13: 00007FF675155581 node_api_throw_syntax_error+69617
  14: 00007FF67516CE2D node_api_throw_syntax_error+166045
  15: 00007FF6751A8CB5 node::FreeEnvironment+133
  16: 00007FF674FEA1E8 RSA_meth_get_flags+159912
  17: 00007FF674FE51B8 RSA_meth_get_flags+139384
  18: 00007FF6751C9B6D uv_poll_stop+237
  19: 00007FF676365180 inflateValidate+153328
  20: 00007FFF5CFE257D BaseThreadInitThunk+29
  21: 00007FFF5F0AAA58 RtlUserThreadStart+40
   ELIFECYCLE  Command failed with exit code 134.
  ```
  </details>

I'm starting to think about an environment one. Do you also use [`nvm`](https://github.com/nvm-sh/nvm) on that windows machine?

**Comment by murisceman** [comment]
I'm out of guesses for now... If a solution pops up, I will definitely let you know. And yes, I'm using `nvm` on Windows.

**Comment by murisceman** [comment]
Perhaps this will resolve the issue: https://github.com/pruvious/pruvious/issues/14#issuecomment-2002450350

**Comment by Sandros94** [comment]
> Perhaps this will resolve the issue: [#14 (comment)](https://github.com/pruvious/pruvious/issues/14#issuecomment-2002450350)

Interesting, I'll test it as I'm able to. 
I was also wondering if sqlite3 has limitations with windows dev drives

**Comment by Sandros94** [comment]
Sorry for the delay, yes indeed via `postgres` it works, this means that I'm also facing issue with `sequelize`.

Closing this one and I'm going to participate in #14
