### ISSUE TITLE
Uploading images gives me the error "File is not defined"

### ISSUE THREAD

**Issue by broadsign-lekevoid** [pruvious/pruvious#48]
I try to upload a PNG image to the media library, and I get the error "File is not defined". 
This is on a whole new, barebones project.

The little red box in the bottom right corner says : 
```
at UploadsQueryBuilder.validate (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\collections\uploads-query-builder.js:278:38)
at UploadsQueryBuilder.create (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\collections\query-builder.js:1001:30)
at UploadsQueryBuilder.create (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\collections\uploads-query-builder.js:46:20)
at Object.handler (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\api\collections.js:700:22)
at async /C:/Web/test-company-pruvious/node_modules/h3/dist/index.mjs:1975:19
at async Object.callAsync (/C:/Web/test-company-pruvious/node_modules/unctx/dist/index.mjs:72:16)
at async Server.toNodeHandle (/C:/Web/test-company-pruvious/node_modules/h3/dist/index.mjs:2266:7)
```

My terminal says : 
```
 ERROR  [nuxt] [request error] [unhandled] [500] File is not defined
  at UploadsQueryBuilder.validate (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\collections\uploads-query-builder.js:278:38)
  at UploadsQueryBuilder.create (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\collections\query-builder.js:1001:30)
  at UploadsQueryBuilder.create (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\collections\uploads-query-builder.js:46:20)
  at Object.handler (C:\Web\test-company-pruvious\node_modules\pruvious\dist\runtime\api\collections.js:700:22)
  at async /C:/Web/test-company-pruvious/node_modules/h3/dist/index.mjs:1975:19
  at async Object.callAsync (/C:/Web/test-company-pruvious/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/C:/Web/test-company-pruvious/node_modules/h3/dist/index.mjs:2266:7)
```

Could it be happening because I haven't set up a S3 or other external storage, or any DB (SQLite or else) ? The documentation seems to say that local storage should work, but maybe I'm misunderstanding.

Here's my nuxt.config.js : 
```
export default defineNuxtConfig({
	compatibilityDate: "2024-04-03",
	devtools: { enabled: true },

	modules: ["@nuxtjs/google-fonts", "@nuxtjs/tailwindcss", "pruvious"],

	googleFonts: {
		families: {
			Lato: {
				wght: [400, 700],
				ital: [400, 700],
			},
			Poppins: [500],
		},
	},

	pruvious: {
		jwt: {
			secretKey: "...",
		},
		language: {
			// List of supported languages in the CMS
			supported: [
				{ code: "en", name: "English" },
				{ code: "fr", name: "Français" },
				{ code: "es", name: "Español" },
				{ code: "de", name: "Deutsch" },
				{ code: "jp", name: "日本語" },
				{ code: "cn", name: "中文" },
			],

			// Default language
			primary: "en",

			// Whether to prefix the primary language in the URL
			prefixPrimary: false,

			// The local storage key to store the active language
			localStorageKey: "language",
		},
		uploads: {
			drive: {
				type: "local",
				path: "./.uploads",
				urlPrefix: "uploads",
			},
		},
	},
});
```

Thank you for your help !

**Comment by murisceman** [comment]
The minimum version of Node.js for Pruvious is `v20`. It should fine work after updating.

**Comment by broadsign-lekevoid** [comment]
Thank you sir ! You are a gentleman and a scholar.

**Comment by abbjetmus** [comment]
Hi!

I'm still getting this issue although using node 20.18 not sure if anything i cached with older versions of node.

```
       v18.17.1
->     v20.18.0
         system
default -> 20.18 (-> v20.18.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v20.18.0) (default)
stable -> 20.18 (-> v20.18.0) (default)
lts/* -> lts/iron (-> v20.18.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.21.3 (-> N/A)
lts/gallium -> v16.20.2 (-> N/A)
lts/hydrogen -> v18.20.4 (-> N/A)
lts/iron -> v20.18.0
```

**Comment by murisceman** [comment]
Hi @abbjetmus! That's strange. The `File` interface should be available in `v20.18.0`. Could you try using `v22`?

**Comment by abbjetmus** [comment]
I don't know, get same error using v22.9.1

```error
ERROR  [nuxt] [request error] [unhandled] [500] File is not defined
  at UploadsQueryBuilder.validate (./node_modules/.pnpm/pruvious@3.13.1_vue@3.5.12/node_modules/pruvious/dist/runtime/collections/uploads-query-builder.js:278:38)  
  at UploadsQueryBuilder.create (./node_modules/.pnpm/pruvious@3.13.1_vue@3.5.12/node_modules/pruvious/dist/runtime/collections/query-builder.js:1001:30)  
  at UploadsQueryBuilder.create (./node_modules/.pnpm/pruvious@3.13.1_vue@3.5.12/node_modules/pruvious/dist/runtime/collections/uploads-query-builder.js:46:20)  
  at Object.handler (./node_modules/.pnpm/pruvious@3.13.1_vue@3.5.12/node_modules/pruvious/dist/runtime/api/collections.js:700:22)  
  at async ./node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:1978:19  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.13.0/node_modules/h3/dist/index.mjs:2270:7)
```

**Comment by abbjetmus** [comment]
I can't get it to work unfortunetly!

**Comment by murisceman** [comment]
What does `console.log(process.version)` output? You can try adding this to `nuxt.config.ts`.

**Comment by abbjetmus** [comment]
You're right it's insisting on using v18.6.1 couldn't get  pnpm to pick up newer versions of node how ever I tried. Changed to npm and it picks up v22.9.1 and works as intended. Thank you!
