### ISSUE TITLE
BUG: Postgres UTF-8 errors after running for 30 mins

### ISSUE THREAD

**Issue by Flexusma** [pruvious/pruvious#51]
<img width="316" alt="image" src="https://github.com/user-attachments/assets/0a8e8c6b-2556-4129-a91f-cba104ac54c5">

After running for a bit (about 30 mins) my prod instance doesn't allow saving posts/pages and settings. A postgres error about wrong utf-8 bytes is thrown.

Restarting the container fixes this issue, I tried digging around the source a bit but was not able to identify a specific part of pruvious that might cause this.

Any help would be appreciated as this is kinda annoying for prod use.

Thanks 

(No error logs printed to stdout, the error is returned plain text as a raw http response)

**Comment by murisceman** [comment]
This error comes directly from PostgreSQL when attempting to write a zero byte as part of a string. Could you try to log the query causing it?

**Comment by Flexusma** [comment]
I think my postgres data dir got corrupted due to some funky ceph rbd double mount issues :/ I'll set up a new db and see if this happens again. Btw is there any convenient way to back up a prouvious instance and DB?

**Comment by murisceman** [comment]
You can use the command `npx pruvious backup` in your project directory to create and restore backups, but this will only work if you have set up your site through the Pruvious CLI. Otherwise, just dump the database and download the `.uploads` directory.

**Comment by Flexusma** [comment]
Thanks for the advice. I'm deploying custom built docker image via CI to swarm/k8s so that was sadly not an option. Btw, would you be open to me writing a .md guide on how to do that as a PR? Since the pruvious.com website is not public on gh, that might be an easy way to allow other people to easily deploy on docker-based systems.

**Comment by murisceman** [comment]
Absolutely, that would be very helpful. Thank you!

**Comment by Flexusma** [comment]
https://github.com/pruvious/pruvious/pull/55

Crossref for later

**Comment by v-moravec** [comment]
Hello,

I tried to use the docker compose file, but it keeps failing with sqlite error - I want to use postgres.

```bash
 > [build 9/9] RUN pnpm build:                                                                                                                                                            
#0 0.757                                                                                                                                                                                  
#0 0.757 > nuxt-app@ build /app                                                                                                                                                           
#0 0.757 > nuxt build                                                                                                                                                                     
#0 0.757                                                                                                                                                                                  
#0 0.950 Nuxt 3.13.1 with Nitro 2.9.7
#0 1.836 
#0 1.836  WARN  The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
#0 1.836 
#0 2.043 [nuxt:tailwindcss] ℹ Using Tailwind CSS from ~/assets/css/tailwind.css
#0 4.592 
#0 4.592  ERROR  Error while requiring module pruvious: Error: /app/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3/build/Release/node_sqlite3.node: invalid ELF header
#0 4.592 
#0 4.593 
#0 4.593  ERROR  /app/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3/build/Release/node_sqlite3.node: invalid ELF header
#0 4.593 
#0 4.593   at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
#0 4.593   at Module.load (node:internal/modules/cjs/loader:1208:32)
#0 4.593   at Module._load (node:internal/modules/cjs/loader:1024:12)
#0 4.593   at Module.require (node:internal/modules/cjs/loader:1233:19)
#0 4.593   at require (node:internal/modules/helpers:179:18)
#0 4.593   at bindings (node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:112:48)
#0 4.593   at node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3/lib/sqlite3-binding.js:1:112
#0 4.593   at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
#0 4.593   at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
#0 4.593   at node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3/lib/sqlite3.js:2:17
#0 4.593   at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
#0 4.593   at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
#0 4.593   at node_modules/.pnpm/pruvious@3.13.0_encoding@0.1.13_rollup@4.21.2_vue@3.5.1_webpack-sources@3.2.3/node_modules/pruvious/dist/runtime/instances/database.js:9:1
#0 4.593   at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
#0 4.593   at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
#0 4.593   at node_modules/.pnpm/pruvious@3.13.0_encoding@0.1.13_rollup@4.21.2_vue@3.5.1_webpack-sources@3.2.3/node_modules/pruvious/dist/runtime/main.js:15:17
#0 4.593   at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
#0 4.593   at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
#0 4.593   at node_modules/.pnpm/pruvious@3.13.0_encoding@0.1.13_rollup@4.21.2_vue@3.5.1_webpack-sources@3.2.3/node_modules/pruvious/dist/module.mjs:11:13
#0 4.593   at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
#0 4.593   at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
#0 4.593   at requireModule (node_modules/.pnpm/@nuxt+kit@3.13.1_magicast@0.2.11_rollup@4.21.2_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2243:26)
#0 4.593   at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.13.1_magicast@0.2.11_rollup@4.21.2_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2518:92)
#0 4.593   at async installModule (node_modules/.pnpm/@nuxt+kit@3.13.1_magicast@0.2.11_rollup@4.21.2_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2470:47)
#0 4.593   at async initNuxt (node_modules/.pnpm/nuxt@3.13.1_@parcel+watcher@2.4.1_@types+node@22.5.4_@upstash+redis@1.34.0_encoding@0.1.13_io_4yshitgul7wkygjlmgll42ukl4/node_modules/nuxt/dist/index.mjs:4493:5)
#0 4.593   at async loadNuxt (node_modules/.pnpm/nuxt@3.13.1_@parcel+watcher@2.4.1_@types+node@22.5.4_@upstash+redis@1.34.0_encoding@0.1.13_io_4yshitgul7wkygjlmgll42ukl4/node_modules/nuxt/dist/index.mjs:4660:5)
#0 4.593   at async Module.loadNuxt (node_modules/.pnpm/@nuxt+kit@3.13.1_magicast@0.2.11_rollup@4.21.2_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2664:19)
#0 4.593   at async Object.run (node_modules/.pnpm/nuxi@3.13.1/node_modules/nuxi/dist/chunks/build.mjs:77:18)
#0 4.593   at async runCommand$1 (node_modules/.pnpm/nuxi@3.13.1/node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1648:16)
#0 4.593   at async runCommand$1 (node_modules/.pnpm/nuxi@3.13.1/node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1639:11)
#0 4.593   at async runMain$1 (node_modules/.pnpm/nuxi@3.13.1/node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1777:7) 
#0 4.593 
#0 4.593 
#0 4.594 
#0 4.594  ERROR  /app/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3/build/Release/node_sqlite3.node: invalid ELF header
#0 4.594 
#0 4.640  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: executor failed running [/bin/sh -c pnpm build]: exit code: 1
```
I set env variable `NUXT_PRUVIOUS_DATABASE` everywhere I could, but I get this error anyway. Did you encounter this or have any idea how to fix it?

**Comment by v-moravec** [comment]
Nevermind.. Everything works now, I forgot to add .dockerignore, so I was copying `node_modules` folder, which led to this error.

Btw - https://github.com/pruvious/pruvious/blob/main/docker/docker-compose.yml#L17 if I'm not mistaken, this should be `ports` instead of `networks`.

**Comment by Flexusma** [comment]
Yeah, good catch! I'll open a quick pr :) The docker-compose file is used by us in a swarm environment, where no ports are needed, we instead isolate containers with custom networks. I must've missed changing that one line when editing the file for gh.

**Comment by Flexusma** [comment]
Also, I think @murisceman we can close this issue now, as this was originally caused by a broken postgres data dir :)
