### ISSUE TITLE
[Bug] 500: unref() is not a function

### ISSUE THREAD

**Issue by andreasvirkus** [pruvious/pruvious#56]
Hi Muris! When using the internationalization method from
```js
import { _ } from '#pruvious/client'
```

The prod build of the site fails to load:
```sh
[nuxt-app] vue:error: 0.352ms
[nitro] [unhandledRejection] TypeError: unref(...) is not a function
    at file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/build/default-zreBDqeV.mjs:366:163
    at renderFnWithContext (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:314:13)
    at ssrRenderSlotInner (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:114:17)
    at ssrRenderSlot (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:96:3)
    at _sfc_ssrRender (file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/build/Container-DAivcQ4d.mjs:8:3)
    at renderComponentSubTree (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:444:9)
    at renderComponentVNode (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:394:12)
    at ssrRenderComponent (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
    at file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/build/default-zreBDqeV.mjs:337:13
    at renderComponentSubTree (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:444:9)
[nitro-runtime] error: 0.03ms
```

This is what my `./translatable-strings/default.en.ts` looks like
```js
import { defineTranslatableStrings } from '#pruvious'

export default defineTranslatableStrings({
  domain: 'default',
  language: 'en',
  strings: {
    footer_copyright: 'All rights reserved',
    footer_privacy_policy: 'Privacy policy',
    footer_contact: 'Get in touch',
    footer_social_media: 'Social media',
    footer_address: 'Address',
  },
})
```

And I have a `components/Footer.vue` file that uses it:
```html
<p>{{ _('footer_copyright') }}</p>
```

As soon as I comment out the `_()` usage, the prod bundle works as expected (but it works fine with the dev server)

**Comment by murisceman** [comment]
Hey, which Pruvious and Nuxt version are you using?

**Comment by andreasvirkus** [comment]
I got the 500 with both of these combinations:

1. initially I was on the `3.12.7` pruvious version and the Nuxt version that was logged to be compatible (because when just updating Nuxt, it gave a warning)
```
nuxt: 3.12.4
pruvious: 3.12.7
```

2. then tried updating both
```
nuxt: 3.13.1
pruvious: 3.12.8
```

**Comment by murisceman** [comment]
Hmm, I cannot reproduce this. Can you try to replicate the error in [this repo](https://github.com/murisceman/issue-56)? That would help me a lot in identifying the issue.

**Comment by andreasvirkus** [comment]
Hmm, I also can't replicate it stand-alone so must be a mixture of things. I think the [color-mode](https://color-mode.nuxtjs.org/) module is causing issues, because I see hydration warnings & this bizarre ref error in the template (which does seem related to `unref`)

![Screenshot 2024-09-13 at 22 31 05](https://github.com/user-attachments/assets/578f57e4-77e0-47b2-83b6-f78991850218)


Weirdly enough now when bumping all the deps to the latest versions (including Vue), then in the dev server I only see the raw i18n keys, but in the prod build everything works fine, do you know what might be causing this? 🤔 

![Screenshot 2024-09-13 at 22 27 06](https://github.com/user-attachments/assets/c041db27-086c-447c-875b-80115b25e1aa)

**Comment by andreasvirkus** [comment]
Interesting. Once I saved my settings collection (where I store my navigation menus), the translated strings issue also fixed itself 🤔 

I currently have no pending issues, so sorry for the journey 😅

**Comment by andreasvirkus** [comment]
Should I remove `.cache/` (and also `.pruvious/`?) between builds when hunting down these types of issues that only occur in the prod builds? What I'm currently doing after each change is just

```
pnpm run build && node ./.output/server/index.mjs
```

Still noticing the unref 500 error sometimes

![Screenshot 2024-09-14 at 11 39 59](https://github.com/user-attachments/assets/afffcf92-8621-4b3c-bb1b-f0bf770e595c)
![Screenshot 2024-09-14 at 11 40 10](https://github.com/user-attachments/assets/2fbc144e-9a56-4d46-8caa-49b67fc8ce8f)
![Screenshot 2024-09-14 at 11 41 00](https://github.com/user-attachments/assets/8718b049-54a8-4155-808d-32ec84dff75d)
![Screenshot 2024-09-14 at 11 41 06](https://github.com/user-attachments/assets/7ce0c2e4-5ee5-424c-aea0-aa589706226f)

**Comment by murisceman** [comment]
> Edit: I did notice the translations have a flash in the dev server, first showing up as the keys. Are they translated on the client?

They should be translated on the server since they use SSR-friendly composables. The `default` translatable strings domain is preloaded in `<PruviousPage />`.

https://github.com/pruvious/pruvious/blob/fe2626bd4b5b9938f9ae48111f24253aecc7212d/src/runtime/components/misc/Page.vue#L29

And `PruviousPage` is called here:

https://github.com/pruvious/pruvious/blob/fe2626bd4b5b9938f9ae48111f24253aecc7212d/src/runtime/pages/%5B...slug%5D.vue#L1-L3

Do you use custom `pages` in your project? If so, you can try preloading the strings manually, as `<PruviousPage />` won't be called. The `loadTranslatableStrings` function is smart enough to prevent unnecessary additional requests after the strings have been loaded.

**Comment by andreasvirkus** [comment]
Sorry for the spam, doing a brain-dump as I go. When running with `node --trace-warnings`, it reports that this line in my `.output/server/chunks/build/` errors out:

```

[nuxt-app] vue:error: 0.174ms
[nitro] [unhandledRejection] TypeError: unref(...) is not a function
    at file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/build/default-DbgWjaxX.mjs:299:163
    at renderFnWithContext (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:314:13)
    at ssrRenderSlotInner (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:114:17)
    at ssrRenderSlot (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:96:3)
    at _sfc_ssrRender (file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/build/Container-DAivcQ4d.mjs:8:3)
    at renderComponentSubTree (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:444:9)
    at renderComponentVNode (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:394:12)
    at ssrRenderComponent (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
    at file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/build/default-DbgWjaxX.mjs:270:13
    at renderComponentSubTree (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:444:9)
[nitro-runtime] error: 0.018ms
[nitro-runtime] afterResponse: 0.017ms
[nuxt-app] app:error: 0.004ms
[nitro-runtime] error: 0.132ms
[nitro-runtime] request: 0.053ms
[nuxt-app] page:loading:start: 0.004ms
[nuxt-app] app:created: 0.136ms
[nuxt-app] vue:setup: 0.002ms
[nuxt-app] app:rendered: 0.002ms
[nitro-runtime] render:html: 0.283ms
[nitro-runtime] render:response: 0.887ms
[nitro-runtime] beforeResponse: 0.005ms
(node:47605) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
    at handledRejection (node:internal/process/promises:283:23)
    at promiseRejectHandler (node:internal/process/promises:192:7)
    at Promise.then (<anonymous>)
    at nestedUnrollBuffer (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:636:19)
    at /Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:645:16
    at async renderToString (/Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:675:18)
    at async Object.renderToString$1 [as renderToString] (file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/routes/renderer.mjs:160:18)
    at async Object.renderToString (file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:174:20)
    at async file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/routes/renderer.mjs:248:21
    at async Object.handler (file:///Users/andreasvirkus/code/kanban/winstonwolf/website/.output/server/chunks/routes/renderer.mjs:20:22)
[nitro-runtime] afterResponse: 0.004ms
```

```
_push2(`<div class="flex flex-col gap-8"${_scopeId}><div class="flex flex-col"${_scopeId}><h3 class="text-black"${_scopeId}>${ssrInterpolate(unref(_2)("footer_address"))}</h3><address${_scopeId}><a class="content-link not-italic contrast" href="https://maps.app.goo.gl/b8V9monRYbcyfRZy8"${_scopeId}> Telliskivi 60a <br${_scopeId}> Tallinn, 10412 </a></address></div><div class="flex flex-col"${_scopeId}><h3 class="text-black"${_scopeId}>${ssrInterpolate(unref(_2)("footer_social_media"))}</h3>`);
```

If I comment out the `_()` usage in the Footer component, the resulting build bundle is this, and the page renders

```
_push2(`<div class="flex flex-col gap-8"${_scopeId}><div class="flex flex-col"${_scopeId}><h3 class="text-black"${_scopeId}> Address </h3><address${_scopeId}><a class="content-link not-italic contrast" href="https://maps.app.goo.gl/b8V9monRYbcyfRZy8"${_scopeId}> Telliskivi 60a <br${_scopeId}> Tallinn, 10412 </a></address></div><div class="flex flex-col"${_scopeId}><h3 class="text-black"${_scopeId}> Social media </h3>`);
```

**Comment by andreasvirkus** [comment]
No custom pages in use

![Screenshot 2024-09-14 at 14 17 45](https://github.com/user-attachments/assets/a59b67ef-7bbc-4552-a219-5b0fbabc3a51)

**Comment by murisceman** [comment]
If you'd like, you can invite me to your project repository or a fork so I can take a look by tomorrow.

**Comment by andreasvirkus** [comment]
Thank you so much for the offer! Invite sent ❤️

**Comment by murisceman** [comment]
Thanks for the invite! I was able to replicate the error on my end. It seems that the translation functions `_` and `__` cannot be used in slots. 😕

If you place `{{ _('footer_copyright') }}` outside of `<Container />` in `Footer.vue`, it will work, though I'm not sure why yet. As a workaround, you can use the string directly instead of the function, like this:

```vue
<template>
  <Container>
    {{ footerCopyright }}
  </Container>
</template>

<script lang="ts" setup>
import { _, loadTranslatableStrings } from '#pruvious/client'

await loadTranslatableStrings('default')

const footerCopyright = _('footer_copyright')
</script>
```

Regarding your question about cache issues, I recommend disabling `pruvious.pageCache` in your `nuxt.config.ts` when dealing with situations like this. The incident where you saved your settings collection cleared the `.cache` folder, which is why you noticed changes afterward.

**Comment by andreasvirkus** [comment]
Thanks for the quick response! Perfectly fine with the workaround for now

**Comment by vanling** [comment]
👀  I had the same error 👀 thanks for this issue and pointing in the right direction. Removed a translatable from header and all is good again 💯

**Comment by Flexusma** [comment]
FYI just mentioning that this basically makes vue-shadcn incompatible with translatable strings since they make heavy use of slots. (Just spent a couple hours trying to figure out what the hell I was doing wrong)
